### ISSUE TITLE
Error after install plugin on redmine 3.3.0

### ISSUE THREAD

**Issue by betonetotbo** [stpl/redmine_mention_plugin#16]
I'm using Bitnami Redmine stack based on Redmine 3.3.0 (https://bitnami.com/stack/redmine-plus-agile).

Here is the apache log:

```
[ 2016-09-19 11:31:53.3372 12933/7f1ad091f700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is 04785e47. Please see earlier logs for details abils about the error.
App 13248 stdout:
App 13248 stdout: An error occurred while loading the routes definition of redmine-mention plugin (/opt/bitnami/apps/redmineplusagile/htdocs/plugins/redmine-mention/config/routes.rb): You should not use the 'match' method in your router without specifying an HTTP method.
App 13248 stdout: If you want to expose your action to both GET and POST, add 'via: [:get, :post]' option.
App 13248 stdout: If you want to expose your action to GET, use 'get' in the router:
App 13248 stdout:   Instead of: match "controller#action"
App 13248 stdout:   Do: get "controller#action".
App 13248 stdout:
[ 2016-09-19 11:32:17.8811 12933/7f1ad37fb700 App/Implementation.cpp:287 ]: Could not spawn process for application /opt/bitnami/apps/redmineplusagile/htdocs/: An error occured while starting up the preloader.
  Error ID: 95ef5ab7
  Error details saved to: /tmp/passenger-error.ptkKD6
  Message from application: exit (SystemExit)
  /opt/bitnami/apps/redmineplusagile/htdocs/config/routes.rb:376:in 'exit'
  /opt/bitnami/apps/redmineplusagile/htdocs/config/routes.rb:376:in 'rescue in block (2 levels) in <top (required)>'
  /opt/bitnami/apps/redmineplusagile/htdocs/config/routes.rb:372:in 'block (2 levels) in <top (required)>'
  /opt/bitnami/apps/redmineplusagile/htdocs/config/routes.rb:369:in 'glob'
  /opt/bitnami/apps/redmineplusagile/htdocs/config/routes.rb:369:in 'block in <top (required)>'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in 'instance_exec'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in 'eval_block'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:410:in 'draw'
  /opt/bitnami/apps/redmineplusagile/htdocs/config/routes.rb:18:in '<top (required)>'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in 'load'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in 'block in load'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in 'load_dependency'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in 'load'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in 'block in load_paths'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in 'each'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in 'load_paths'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:16:in 'reload!'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:26:in 'block in updater'
  /opt/bitnami/apps/redmineplusagile/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/file_update_checker.rb:75:in 'call'
```

**Comment by popov-ilya** [comment]
You can try this fork https://github.com/hryamzik/redmine_mention_plugin, some issues were fixed.
