### ISSUE TITLE
redmine 2.3.2 cannot install

### ISSUE THREAD

**Issue by fengyedou** [stpl/redmine_mention_plugin#7]
Hi， I installed under redmine 2.3.2, there is such error

rake aborted!
undefined method `descendants' for Mention:Module

Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by fengyedou** [comment]
D:\BitNami\redmine-2.3.2-0\apps\redmine\htdocs>bundle exec rake redmine:plugins
NAME=redmine_mention_plugin RAILS_ENV=production
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://ruby
gems.org' if not.
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/watchr-0.7/lib/watchr.r
b:111: Use RbConfig instead of obsolete and deprecated Config.
rake aborted!
undefined method `descendants' for Mention:Module
<internal:prelude>:10:in`synchronize'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
 (required)>'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in`blo
ck (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by fengyedou** [comment]
D:\BitNami\redmine-2.3.2-0\apps\redmine\htdocs>bundle exec rake redmine:plugins
NAME=redmine_mention_plugin RAILS_ENV=production
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://ruby
gems.org' if not.
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/watchr-0.7/lib/watchr.r
b:111: Use RbConfig instead of obsolete and deprecated Config.
rake aborted!
undefined method `descendants' for Mention:Module
<internal:prelude>:10:in`synchronize'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
 (required)>'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in`blo
ck (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by fengyedou** [comment]
D:\BitNami\redmine-2.3.2-0\apps\redmine\htdocs>bundle exec rake redmine:plugins
NAME=redmine_mention_plugin RAILS_ENV=production
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://ruby
gems.org' if not.
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/watchr-0.7/lib/watchr.r
b:111: Use RbConfig instead of obsolete and deprecated Config.
rake aborted!
undefined method `descendants' for Mention:Module
<internal:prelude>:10:in`synchronize'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
 (required)>'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in`blo
ck (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by fengyedou** [comment]
D:\BitNami\redmine-2.3.2-0\apps\redmine\htdocs>bundle exec rake redmine:plugins
NAME=redmine_mention_plugin RAILS_ENV=production
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://ruby
gems.org' if not.
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/watchr-0.7/lib/watchr.r
b:111: Use RbConfig instead of obsolete and deprecated Config.
rake aborted!
undefined method `descendants' for Mention:Module
<internal:prelude>:10:in`synchronize'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
 (required)>'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in`blo
ck (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
